version: "2"
services:
  soctopus:
    container_name: soctopus
    build: ./
    image: soctopus
    networks:
      - so-elastic-net
    volumes:
      - ~/soctopus/SOCtopus.conf:/SOCtopus/SOCtopus.conf:ro 
    ports:
      - "0.0.0.0:7000:7000"
networks:
  so-elastic-net:
    external: true
